### ISSUE TITLE
LINT-75(feedback): Impossible to disable rules by customized ruleIds

### ISSUE THREAD

**Issue by Krakazybik** [feature-sliced/eslint-config#78]
### Description
Impossible to disable rules by customized ruleIds
By IDE and by manual disabling

### Reference
https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2055299

**Comment by Krakazybik** [comment]
> Не обязательно кста под каждую проблему ишьюс так создавать)

Пусть так будет, а то потом концов не найдем.

**Comment by azinit** [comment]
> > Не обязательно кста под каждую проблему ишьюс так создавать)
> 
> Пусть так будет, а то потом концов не найдем.

Поч?)

Просто же ссылаешься на оформленный тред-проблему , не? 🤔
