### ISSUE TITLE
LINT: (Feedback) Refine bootstraping of linting

### ISSUE THREAD

**Issue by azinit** [feature-sliced/eslint-config#86]
## Problem

- [x] Redundant TS settings `alwaysTryTypes`?
- [ ] Too much dependencies to install
- [ ] Too much steps to do for quick setuping of linting

## Reference

https://github.com/feature-sliced/eslint-config/discussions/75#discussioncomment-2036860

**Comment by azinit** [comment]
About `alwaysTryTypes`

![image](https://user-images.githubusercontent.com/42924400/152119675-df45b9b5-bd9f-4df5-9676-2d631128fe9e.png)

**Comment by azinit** [comment]
About bootstrapping

![image](https://user-images.githubusercontent.com/42924400/152119912-21f306b4-1d6d-4a12-bf69-dabb487ef628.png)

**Comment by Krakazybik** [comment]
Сегодня весёлое настроение!

> покряхтел - писал однозначно ленивый дед!

> Too much dependencies to install
А может мне ваш ТС и не нужОн!

>  Too much steps to do for quick setuping of linting
3 шага, на один проект. Мы же каждый день по 19 штук запускаем ?  xD

**Comment by azinit** [comment]
Надо `npx @feature-sliced/lint` сразу, ну))

**Comment by Krakazybik** [comment]
> Надо npx @feature-sliced/lint сразу, ну))

А  как же: не нужОн мне ваш ТС?

**Comment by azinit** [comment]
@Krakazybik Для "quickInstall" предлагаю к этому присмотреться 🤔 

> **TLDR:** Быстрый сетапинг через peerDeps

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json#L89

**Comment by azinit** [comment]
А для "alwaysTryTypes" - я бы проверил, насколько он нужен для нашего `boundaries/elements-types` 🤔 

Т.к. помню при тестировании на других проектах - иногда работало и без alwaysTryTypes
(а там где не работало, возможно я коряво typescript-parser поставил - предлагаю проверить еще раз, чтобы людям не приходилось обмазываться TS конфигами, которые в рамках нашего eslint-config не нужны)

**Comment by Krakazybik** [comment]
@azinit Какие изыскания у меня вышли на данный момент:
- `yarn` - не умеет в peerDep's
- `eslint` -  насильное втягивание нашей версии - может привести к поломке линтера в проекте.
- `eslint-plugin-import`, `eslint-plugin-boundaries` по идее можно затащить в обычные dep's, но надо тестить с npm, yarn, pnpm насколько корректно это всё подцепится в каждом случае, чтоб не получилось что где-то не будут подцепляться зависимости.

Теперь идея с `npx` не кажется овер-инженерной. :thinking: Попробую по ресёрчить в этом направлении.

**Comment by azinit** [comment]
@Krakazybik спасибо что расписал!
Кажется что да, npx вполне компромиссный и не сильно затратный вариант остается 🤔

**Comment by illright** [comment]
Ну я вот тут сейчас поразмыслил, погуглил про то, что такое плагин, что такое конфиг, понял, что беда. Не знаю даже, как и улучшить. Тут я бы, наверное, предложил ридми немного переписать, чтоб было меньше нагрузки на моск.

1. Убрать пункт про необходимость установки ESLint
   Во-первых, если люди не знают, что такое ESLint, им не сюда  
   Во-вторых, пакетные менеджеры умеют кричать на отсутствие пир-зависимостей, давайте отгрузим на них эту нелегкую ношу работать с пользователями, которые не успели еще поставить себе ESLint
2. Убрать команды для `yarn`
   Обычно это, конечно, хорошо — иметь их, но тут каждая команда сопровождается огромным списком целей установки, из-за чего блок команд визуально больше, чем он есть на самом деле. Думаю, мы не сильно нагрузим пользователей `yarn`, если попросим их написать `yarn add -D` самим.
3. `(for recommended rules). You can omit the eslint-config postfix`
   Вот это всё тоже просто убрать) не знаю, зачем оно там

С тайпскриптом, конечно, какая-то срань. Понимаю, что от нас тут ничего не зависит. Решение тут вижу, но сначала расскажу о том, как я себя чувствовал, проходя через этот процесс установки:

<details><summary>Вот примерно мои мысли тогда</summary>

1. Так, надо установить ESLint. У меня уже есть ESLint, зачем мне напоминать?
2. Так, надо установить конфигу и зависимости. Блин, почему так много зависимостей(( что все это такое вообще, и зачем
3. Так, надо добавить конфигу в `eslintrc`, тут стандартно, sample text пропускаем
4. Так, TypeScript-only. У меня тайпскрипт на проекте, надо сделать, открываем спойлер
5. Боже, еще такая же пачка зависимостей(( и ведь по-любому какая-то из них у меня уже есть, сейчас надо еще разбираться в этом, чтоб не накатить чего лишнего

</details>

Решение: отгрузить процесс настройки TS для ESLint на другой туториал, добавив на него ссылку. `@typescript-eslint/eslint-plugin @typescript-eslint/parser` уже установлены у тех людей, у которых работает ESLint с TS. Тогда TS-специфичная установка становится намного проще:
* накатить `eslint-import-resolver-typescript`
* добавить мини-блок в `settings` в `eslintrc`

**Comment by azinit** [comment]
@illright Много с чем согласен, но вот "сделать неявным описание зависимостей, и уж тем более вынести в другой туториал" - кмк уже чересчур

Причем тут не уровень разработчика будет влиять, а в целом отношение "к неявностям"
Т.е. человек установит конфиг, думая что все ОК
А там нате - и он не запускается из-за плагинов

И тогда уже вместо твоих описанных мыслей будет что-то типа `Блен, а сложно было в описание добавить плагины?!`
(а у некоторых отторжение может быть еще на этапе прочтения README, т.к. по нему непонятно, что за начинка)

---

Я бы на самом деле тоже постарался оставить варик с peerDeps, но увы для того же ярна он фигово работает
(да и немного неявности есть)


Пока все склоняется к тому, чтобы npx скрипт запилить, наподобие [eslint-kit](https://www.npmjs.com/package/eslint-kit#installation-using-eslint-kit-cli)
