### ISSUE TITLE
LINT: Проресерчить решения из OpenSource

### ISSUE THREAD

**Issue by azinit** [feature-sliced/eslint-config#9]
На случай, если найдутся получше для реализации тех же правил

- https://github.com/lydell/eslint-plugin-simple-import-sort
- https://github.com/sverweij/dependency-cruiser
- https://github.com/javierbrea/eslint-plugin-boundaries
- https://eslint.org/docs/4.0.0/rules/sort-imports
- https://github.com/SonarSource/SonarJS

**Comment by illright** [comment]
It seems like no one will do this, and there's not much need.
