### ISSUE TITLE
LINT: (CLI) Add minor refinements

### ISSUE THREAD

**Issue by azinit** [feature-sliced/eslint-config#99]
### Problem

Протестил cli перед публикацией. Есть критичные недоработки, что не проверили при влитии)

- [ ] **Добавить базовые тесты на "запускаемость" cli**
       Не нужно упарываться в тесткейсы, достаточно просто проверить что `npm build + npm start` запускается и не падает для cli
       Т.к. во время отладки при сборке даже ничего не упало, хотя код в мастере по факту не запускался 🤷‍♂️ 
       [(пришлось фиксить налету)](https://github.com/feature-sliced/eslint-config/commit/a7dda7568369ebdbe54cc633ef98c8c5a99e5aff)

    <table>
    <td>

    Функция просто не импортилась в файле
    ![image](https://user-images.githubusercontent.com/42924400/155191702-9b9c83b5-a544-4036-a292-867b1e59cb18.png)

    </td>
    <td>

     Функция не работала после рефакторинга на for...of (забыли Object.keys добавить)
     ![image](https://user-images.githubusercontent.com/42924400/155191707-a645bdcb-e522-4dd7-bf4e-5aae6ab244f5.png)
     </td>
     </table>

- [ ] **Добавить визуальную итеративность установке**
      [В первом прототипе cli](https://user-images.githubusercontent.com/1334019/154853116-5374d7b6-1293-42ec-baad-937fd1b24f97.mp4) каждая зависимость устанавливалась отдельно, что было визуально приятно смотреть - "Минимум лишней инфы. И актуальное обновление статусов"
     Почему-то после рефакторинга теперь все это устанавливается в одну строчку - и для плагинов и для TS
     Нужно вернуть "как было"

     ![image](https://user-images.githubusercontent.com/42924400/155192577-b1b94017-133e-4181-ae48-3a8e27df1d5c.png)

 
- [ ] **Ложно позитивная установка TS зависимостей**
     Проект [eslint-config] явно детектится как не TS-овый (см. консоль на скрине)
     Но при этом хоть и в `ui` передается false-значение, установка TS зависимостей все равно происходит

     ![image](https://user-images.githubusercontent.com/42924400/155191459-74d56c95-58d6-401b-8bbe-e2d1a63b6b9c.png)

**Comment by Krakazybik** [comment]
>  Добавить базовые тесты на "запускаемость" cli
Хочу баш скрипт говорили они =))
